/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Three from 'three';
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props:any) {
  const { nodes, materials } = useGLTF('/ImageToStl.com_project+2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.body}
        position={[-1.364, -1.424, 1.745]}
        rotation={[0.022, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.mettal}
        position={[-1.328, 0.732, 2.085]}
        rotation={[0.022, 0, 0]}
        scale={-0.489}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.001']}
        position={[-1.37, 1.23, 2.068]}
        rotation={[0.022, 0, 0]}
        scale={[0.211, 0.398, 0.211]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.glass}
        position={[-1.34, 1.904, 2.118]}
        rotation={[0.022, 0, 0]}
        scale={0.731}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.mettal}
        position={[-1.318, -1.479, 1.755]}
        rotation={[0.048, 0.023, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials.body}
        position={[-2.444, -0.678, 1.313]}
        rotation={[-1.536, -0.005, 1.572]}
        scale={-0.569}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.marbel}
        position={[-1.4, -5.819, 2.096]}
        rotation={[0.022, 0, 0]}
        scale={[3.885, 3.395, 3.885]}
      />
    </group>
  )
}

useGLTF.preload('/ImageToStl.com_project+2.glb')
